default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "postgres") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mogstudy_development

test:
  <<: *default
  database: mogstudy_test

production:
  primary:
    <<: *default
    database: mogstudy_production

  cache:
    <<: *default
    database: mogstudy_production_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *default
    database: mogstudy_production_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *default
    database: mogstudy_production_cable
    migrations_paths: db/cable_migrate